#!/usr/bin/env node
// Runs on the HOST (via devcontainer.json's initializeCommand), before any
// container is created. Derives a project-unique name so the compose
// project, network, and containers never collide with another checkout
// using this template.
//
// Prerequisites on the host: node on PATH. No npm packages are used here —
// this script is host bootstrapping, not part of the project.

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const scriptDir = __dirname;
const repoRoot = path.resolve(scriptDir, "..", "..");
const workspaceName = path.basename(repoRoot);

// Hash the absolute path (not just the folder name) so two worktrees/clones
// that happen to share a folder name still get distinct project slugs.
const pathHash = crypto.createHash("sha256").update(repoRoot).digest("hex").slice(0, 8);

const projectSlug = `${workspaceName}-${pathHash}`
  .toLowerCase()
  .replace(/[^a-z0-9-]+/g, "-");

const envPath = path.join(scriptDir, ".env");
fs.writeFileSync(
  envPath,
  `# Generated by init-host.js — do not edit by hand, do not commit.\n` +
    `COMPOSE_PROJECT_NAME=${projectSlug}\n` +
    `WORKSPACE_NAME=${workspaceName}\n`
);

console.log(`[iron-proxy] project slug: ${projectSlug}`);
