#!/usr/bin/env node
// Runs on the HOST (via devcontainer.json's initializeCommand), before any
// container is created. Responsible for:
//   1. Deriving a project-unique name so the compose project, network, and
//      containers never collide with another checkout using this template.
//   2. Generating the iron-proxy CA (once) so certs are ready before the
//      proxy and agent containers start.
//
// Prerequisites on the host: node and openssl on PATH. No npm packages are
// used here — this script is host bootstrapping, not part of the project.

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { execFileSync } = require("child_process");

const scriptDir = __dirname;
const repoRoot = path.resolve(scriptDir, "..", "..");
const workspaceName = path.basename(repoRoot);

// Hash the absolute path (not just the folder name) so two worktrees/clones
// that happen to share a folder name still get distinct project slugs.
const pathHash = crypto.createHash("sha256").update(repoRoot).digest("hex").slice(0, 8);

const projectSlug = `${workspaceName}-${pathHash}`
  .toLowerCase()
  .replace(/[^a-z0-9-]+/g, "-");

const envPath = path.join(scriptDir, ".env");
fs.writeFileSync(
  envPath,
  `# Generated by init-host.js — do not edit by hand, do not commit.\n` +
    `COMPOSE_PROJECT_NAME=${projectSlug}\n` +
    `WORKSPACE_NAME=${workspaceName}\n`
);

console.log(`[iron-proxy] project slug: ${projectSlug}`);

const certsDir = path.join(scriptDir, "certs");
fs.mkdirSync(certsDir, { recursive: true });

const caKey = path.join(certsDir, "ca.key");
const caCrt = path.join(certsDir, "ca.crt");

if (!fs.existsSync(caKey) || !fs.existsSync(caCrt)) {
  console.log("[iron-proxy] generating CA certificate...");
  execFileSync("openssl", ["genrsa", "-out", caKey, "4096"], { stdio: "inherit" });
  execFileSync(
    "openssl",
    [
      "req",
      "-x509",
      "-new",
      "-nodes",
      "-key",
      caKey,
      "-sha256",
      "-days",
      "3650",
      "-subj",
      `/CN=${projectSlug} iron-proxy CA`,
      "-addext",
      "basicConstraints=critical,CA:TRUE",
      "-addext",
      "keyUsage=critical,keyCertSign",
      "-out",
      caCrt,
    ],
    { stdio: "inherit" }
  );
  fs.chmodSync(caKey, 0o600);
} else {
  console.log("[iron-proxy] reusing existing CA certificate in ./certs");
}
